import type { Metadata } from "next";
import "./globals.css";
import { I18nProvider } from "@/app/lib/i18nContext";

export const metadata: Metadata = {
  title: "Global Connect ethiopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <I18nProvider>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
