// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/organizers" | "/admin/organizers/[id]" | "/admin/proposals" | "/admin/proposals/[id]" | "/admin/vendors" | "/admin/vendors/[id]" | "/dashboard" | "/login" | "/ministry/proposals" | "/ministry/proposals/[id]" | "/municipal/proposals" | "/municipal/proposals/[id]" | "/organizer/create-event" | "/organizer/dashboard" | "/organizer/events" | "/organizer/proposal-review" | "/organizer/proposals" | "/organizer/proposals/[id]" | "/organizer/proposals/[id]/permit" | "/organizer/proposals/create" | "/organizer/register" | "/organizer/under-review" | "/police/proposals" | "/register" | "/vendor/verification" | "/verify-email"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/api/v1/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin/organizers": {}
  "/admin/organizers/[id]": { "id": string; }
  "/admin/proposals": {}
  "/admin/proposals/[id]": { "id": string; }
  "/admin/vendors": {}
  "/admin/vendors/[id]": { "id": string; }
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/dashboard": {}
  "/login": {}
  "/ministry/proposals": {}
  "/ministry/proposals/[id]": { "id": string; }
  "/municipal/proposals": {}
  "/municipal/proposals/[id]": { "id": string; }
  "/organizer/create-event": {}
  "/organizer/dashboard": {}
  "/organizer/events": {}
  "/organizer/proposal-review": {}
  "/organizer/proposals": {}
  "/organizer/proposals/[id]": { "id": string; }
  "/organizer/proposals/[id]/permit": { "id": string; }
  "/organizer/proposals/create": {}
  "/organizer/register": {}
  "/organizer/under-review": {}
  "/police/proposals": {}
  "/register": {}
  "/vendor/verification": {}
  "/verify-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
