// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/organizers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizers/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/organizers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/organizers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizers">> = Specific
  const handler = {} as typeof import("../../app/admin/organizers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/proposals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/proposals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proposals">> = Specific
  const handler = {} as typeof import("../../app/admin/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vendors">> = Specific
  const handler = {} as typeof import("../../app/admin/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/proposals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../app/ministry/proposals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/proposals">> = Specific
  const handler = {} as typeof import("../../app/ministry/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/municipal/proposals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/municipal/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../app/municipal/proposals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/municipal/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/municipal/proposals">> = Specific
  const handler = {} as typeof import("../../app/municipal/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/contracts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../app/organizer/contracts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/contracts">> = Specific
  const handler = {} as typeof import("../../app/organizer/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/create-event/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/create-event/[id]">> = Specific
  const handler = {} as typeof import("../../app/organizer/create-event/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/create-event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/create-event">> = Specific
  const handler = {} as typeof import("../../app/organizer/create-event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/dashboard">> = Specific
  const handler = {} as typeof import("../../app/organizer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/booking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/booking">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/booking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/budget/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/budget">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/budget/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/operations">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/tasks">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/team">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/venue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/venue">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/venue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/[id]/wrap-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[id]/wrap-up">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/[id]/wrap-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events">> = Specific
  const handler = {} as typeof import("../../app/organizer/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/proposal-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/proposal-review">> = Specific
  const handler = {} as typeof import("../../app/organizer/proposal-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/proposals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../app/organizer/proposals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/proposals/[id]/permit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/proposals/[id]/permit">> = Specific
  const handler = {} as typeof import("../../app/organizer/proposals/[id]/permit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/proposals/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/proposals/create">> = Specific
  const handler = {} as typeof import("../../app/organizer/proposals/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/proposals">> = Specific
  const handler = {} as typeof import("../../app/organizer/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/register">> = Specific
  const handler = {} as typeof import("../../app/organizer/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/organizer/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/requests">> = Specific
  const handler = {} as typeof import("../../app/organizer/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/under-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/under-review">> = Specific
  const handler = {} as typeof import("../../app/organizer/under-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../app/organizer/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/vendors">> = Specific
  const handler = {} as typeof import("../../app/organizer/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organizer/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/wallet">> = Specific
  const handler = {} as typeof import("../../app/organizer/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/police/proposals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/police/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../app/police/proposals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/police/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/police/proposals">> = Specific
  const handler = {} as typeof import("../../app/police/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/contracts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../app/vendor/contracts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/contracts">> = Specific
  const handler = {} as typeof import("../../app/vendor/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/dashboard">> = Specific
  const handler = {} as typeof import("../../app/vendor/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/vendor/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/requests">> = Specific
  const handler = {} as typeof import("../../app/vendor/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/under-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/under-review">> = Specific
  const handler = {} as typeof import("../../app/vendor/under-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/verification">> = Specific
  const handler = {} as typeof import("../../app/vendor/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/wallet">> = Specific
  const handler = {} as typeof import("../../app/vendor/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
